# Generated by Django 6.0.5 on 2026-05-16 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.CharField(max_length=512)),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=20)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urls.shorturl')),
            ],
        ),
    ]
