# Generated by Django 6.0.5 on 2026-05-30 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='clicked_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
